### ISSUE TITLE
Set up initial environment for development in Docker

### ISSUE THREAD

**Issue by StefanSchade** [StefanSchade/nvim-container#1]
## Description:

As a developer, I want to start a Docker container containing a rudimentry development environment including Neovim and Tmux. to continue project work from there.

## Tasks:

- [x] setup git project 
- [x] create initial structure 
- [x] create an initial Dockerfile and a PostCreateScript
- [x] create necessary scripts for convenence

## Considerations:

- delegating some aspects of the setup to a PostCreateScript makes the solution more flexible. It is inspired by the [DevContainer](https://containers.dev/) specification although this does not apply here because we are dedicated to setting up the dev environment, not the project istself.

- not all folders will imediately become visible in git as they might be empty to start with

## Acceptance Criteria:

- repo structure is created
- I can easily start the Container and work with nvim / tmux

**Comment by StefanSchade** [comment]
The run_dev_env script does not reside in the same directory as the docker-compose.yml and only works because of the customary search path up the dir structure. Reference the right docker-componse more directly to make it more explicit, which docker-compose is meant.
